apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
  namespace: homework
  finalizers: []
spec:
  group: otus.homework
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                database:
                  type: string
                  pattern: ^[a-z0-9_-]{1,12}$
                image:
                  type: string
                  pattern: ^.{1,24}$
                password:
                  type: string
                  pattern: ^.{1,12}$
                storage_size:
                  type: string
                  pattern: ^[0-9]{1,3}$
              required:
              - database
              - image
              - password
              - storage_size
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: MySQL
  