apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-role
rules:
- apiGroups: [""]
  resources: ["services","persistentvolumes","persistentvolumeclaims","events"]
  verbs: ["*"]
- apiGroups: ["apps","extensions"]
  resources: ["deployments","deployments/status"]
  verbs: ["*"]
- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["*"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["*"]
