apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app1
  labels:
    app: app1
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginx/nginx
        ports:
        - name: web
          containerPort:  80
          protocol: TCP
        env:
        - name: NGX_VERSION
          value: 1.16.1
