apiVersion: v1
kind: Service
metadata:
  name: homework-monitoring
  namespace: homework
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  labels:
    app: homework-monitoring
spec:
  selector:
    app: homework-monitoring
  type: ClusterIP
  ports:
  - name: homework-monitoring
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: metrics
    protocol: TCP
    port: 9113
    targetPort: 9113