apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-security
  namespace: homework
  labels:
    app: homework-security
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi