---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: homework
  name: nginxconf
data:
  default.conf: |
     server {
       listen       8000;
       server_name  localhost;
       location  /conf  {
           alias /conf;
       }
       location / {
         root /homework;
         rewrite ^ /index.html break; 
        }
      }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: conffile
  namespace: homework
data:
  file: |
    login=admin
    password=qwe123


  